set(CMAKE_BUILD_TYPE RELEASE CACHE STRING "")

set(LLVM_ENABLE_PROJECTS "clang;clang-tools-extra;lld" CACHE STRING "")
set(LLVM_ENABLE_RUNTIMES "compiler-rt;libcxx;libcxxabi" CACHE STRING "")
set(LLVM_TARGETS_TO_BUILD X86;AArch64 CACHE STRING "")

set(COMPILER_RT_INCLUDE_TESTS OFF CACHE BOOL "")
set(DLLVM_BUILD_BENCHMARKS OFF CACHE BOOL "")
set(DLLVM_BUILD_TESTS OFF CACHE BOOL "")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "")
set(LIBCLANG_BUILD_STATIC ON CACHE BOOL "")
set(LLVM_ENABLE_ASSERTIONS OFF CACHE BOOL "")
